include: package:flutter_lints/flutter.yaml

l10n_lint_exempt:
  - lib/l10n/**.arb
  - lib/l10n/app_localizations*.dart
  - lib/debug/**
  - test/goldens/**
  - lib/features/locations/presentation/pages/location_picker_smoke_test_page.dart
  - lib/features/currencies/presentation/pages/money_formatter_showcase_page.dart

analyzer:
  errors:
    avoid_print: error
    prefer_const_constructors: error

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    unawaited_futures: true
