-- 20260717120008_rls_initplan_wrap_hot_tables
--
-- QA E2E perf (PERF-M1, hot read-path subset): wrap auth.uid() in a scalar subselect
-- so Postgres evaluates it once per query (an InitPlan) instead of once per row on the
-- feed / search / chat tables. Semantically IDENTICAL — the same rows match; only the
-- evaluation count changes (advisor `auth_rls_initplan`). Generated + reviewed from
-- pg_policies; row-dependent predicates (publisher_user_id comparisons, EXISTS
-- subqueries, current_user_has_permission) are preserved untouched.
--
-- Verified live 2026-07-17: 0 unwrapped auth.uid() remain on these tables.
--
-- Follow-up (documented, deferred): the ~17 non-hot tables, wrapping
-- current_user_has_permission()/current_user_is_admin(), and merging the 27 duplicate
-- permissive policies. Left for a focused pass — near-zero benefit at current scale and
-- these are security-critical policies.
alter policy conversations_insert_buyer on public.conversations with check (((buyer_user_id = (select auth.uid())) AND (buyer_user_id <> publisher_user_id)));
alter policy conversations_select_member on public.conversations using ((((select auth.uid()) = buyer_user_id) OR ((select auth.uid()) = publisher_user_id)));
alter policy favorites_delete_self on public.favorites using ((user_id = (select auth.uid())));
alter policy favorites_select_self on public.favorites using ((user_id = (select auth.uid())));
alter policy listing_details_select_owner_or_admin on public.listing_details using ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_details.listing_id) AND ((l.publisher_user_id = (select auth.uid())) OR current_user_has_permission('listings.view_all'::text))))));
alter policy listing_details_write_owner on public.listing_details using ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_details.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text])))))) with check ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_details.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text]))))));
alter policy listing_media_owner_delete on public.listing_media using ((EXISTS ( SELECT 1 FROM (listings l JOIN profiles p ON ((p.user_id = l.publisher_user_id))) WHERE ((l.id = listing_media.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text])) AND (p.publisher_status = 'approved'::publisher_status_enum) AND (p.account_status = 'approved'::account_status_enum)))));
alter policy listing_media_owner_insert on public.listing_media with check ((EXISTS ( SELECT 1 FROM (listings l JOIN profiles p ON ((p.user_id = l.publisher_user_id))) WHERE ((l.id = listing_media.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text])) AND (p.publisher_status = 'approved'::publisher_status_enum) AND (p.account_status = 'approved'::account_status_enum)))));
alter policy listing_media_owner_select on public.listing_media using ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_media.listing_id) AND (l.publisher_user_id = (select auth.uid()))))));
alter policy listing_media_owner_update on public.listing_media using ((EXISTS ( SELECT 1 FROM (listings l JOIN profiles p ON ((p.user_id = l.publisher_user_id))) WHERE ((l.id = listing_media.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text])) AND (p.publisher_status = 'approved'::publisher_status_enum) AND (p.account_status = 'approved'::account_status_enum))))) with check ((EXISTS ( SELECT 1 FROM (listings l JOIN profiles p ON ((p.user_id = l.publisher_user_id))) WHERE ((l.id = listing_media.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text])) AND (p.publisher_status = 'approved'::publisher_status_enum) AND (p.account_status = 'approved'::account_status_enum)))));
alter policy listing_prices_select_owner_or_admin on public.listing_prices using ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_prices.listing_id) AND ((l.publisher_user_id = (select auth.uid())) OR current_user_has_permission('listings.view_all'::text))))));
alter policy listing_prices_write_owner on public.listing_prices using ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_prices.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text])))))) with check ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_prices.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text]))))));
alter policy listing_status_history_select_owner on public.listing_status_history using (((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_status_history.listing_id) AND (l.publisher_user_id = (select auth.uid()))))) OR current_user_has_permission('listings.view_all'::text)));
alter policy listing_visibility_select_owner_or_admin on public.listing_visibility using ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_visibility.listing_id) AND ((l.publisher_user_id = (select auth.uid())) OR current_user_has_permission('listings.view_all'::text))))));
alter policy listing_visibility_write_owner on public.listing_visibility using ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_visibility.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text])))))) with check ((EXISTS ( SELECT 1 FROM listings l WHERE ((l.id = listing_visibility.listing_id) AND (l.publisher_user_id = (select auth.uid())) AND (l.status = ANY (ARRAY['draft'::text, 'rejected'::text]))))));
alter policy listings_insert_owner on public.listings with check ((((select auth.uid()) = publisher_user_id) AND (EXISTS ( SELECT 1 FROM profiles p WHERE ((p.user_id = (select auth.uid())) AND (p.publisher_status = 'approved'::publisher_status_enum) AND (p.account_status = 'approved'::account_status_enum))))));
alter policy listings_select_owner on public.listings using (((select auth.uid()) = publisher_user_id));
alter policy listings_update_owner on public.listings using ((((select auth.uid()) = publisher_user_id) AND (status = ANY (ARRAY['draft'::text, 'rejected'::text])) AND (EXISTS ( SELECT 1 FROM profiles p WHERE ((p.user_id = (select auth.uid())) AND (p.publisher_status = 'approved'::publisher_status_enum) AND (p.account_status = 'approved'::account_status_enum)))))) with check ((((select auth.uid()) = publisher_user_id) AND (status = ANY (ARRAY['draft'::text, 'pending_review'::text]))));
alter policy messages_insert_member on public.messages with check (((sender_user_id = (select auth.uid())) AND (EXISTS ( SELECT 1 FROM conversations c WHERE ((c.id = messages.conversation_id) AND (((select auth.uid()) = c.buyer_user_id) OR ((select auth.uid()) = c.publisher_user_id)))))));
alter policy messages_select_member on public.messages using ((EXISTS ( SELECT 1 FROM conversations c WHERE ((c.id = messages.conversation_id) AND (((select auth.uid()) = c.buyer_user_id) OR ((select auth.uid()) = c.publisher_user_id))))));
alter policy messages_update_member on public.messages using ((EXISTS ( SELECT 1 FROM conversations c WHERE ((c.id = messages.conversation_id) AND (((select auth.uid()) = c.buyer_user_id) OR ((select auth.uid()) = c.publisher_user_id))))));
